spring:
  application:
    name: v2data
  servlet:
    context-path: /api
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    logging:
      level:
        root: INFO
        com.rohitvpatil0810: DEBUG
      file:
        path: logs
  config:
    import:
      - optional:cloudflare-secrets.yaml
      - optional:v2data-transcriber-secrets.yaml

server:
  port: 8080
  servlet:
    context-path: /api