spring:
  application:
    name: v2data
  servlet:
    context-path: /api
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  config:
    import: optional:cloudflare-secrets.yaml

server:
  port: 8080
