spring:
  application:
    name: v2data
  servlet:
    context-path: /api
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    logging:
      level:
        root: INFO
        com.rohitvpatil0810: DEBUG
      file:
        path: logs

  datasource:
    url: jdbc:postgresql://localhost:5432/v2data-db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  config:
    import:
      - classpath:spring-mail-secrets.yaml
      - optional:cloudflare-secrets.yaml
      - optional:v2data-transcriber-secrets.yaml

server:
  port: 8080
  servlet:
    context-path: /api

app:
  base-url: http://localhost:8080/api