spring:
  mail:
    host: smtp.email.com
    port: 587
    username: your-email@email.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000