CREATE TABLE verification_tokens (
    id BIGSERIAL PRIMARY KEY,
    hashed_token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expiry_time TIMESTAMP WITHOUT TIME ZONE,
    used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);
